CC = gcc
CFLAGS = -Wall

mainCompile:
	$(CC) $(CFLAGS) main.c -o main 

handler: mainCompile
	./main handler

ignore: mainCompile
	./main ignore

mask: mainCompile
	./main mask

pending: mainCompile
	./main pending
